services:
  n8n:
    image: n8nio/n8n:2.5.2
    container_name: n8n-main
    environment:
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=external
      - N8N_RUNNERS_BROKER_LISTEN_ADDRESS=0.0.0.0
      - N8N_RUNNERS_AUTH_TOKEN=your-secret-here
      - N8N_NATIVE_PYTHON_RUNNER=true
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - N8N_SECURE_COOKIE=false
      # - WEBHOOK_URL=https://n8n.example.com/
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    # etc.

  task-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n-runner
    environment:
      - N8N_RUNNERS_TASK_BROKER_URI=http://n8n-main:5679
      - N8N_RUNNERS_AUTH_TOKEN=your-secret-here
      - N8N_RUNNERS_STDLIB_ALLOW=*
      - N8N_RUNNERS_EXTERNAL_ALLOW=*
      # etc.
    depends_on:
      - n8n

volumes:
  n8n_data: